// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DAL.Entities;

public partial class Country
{
    //public Country() 
    //{
    //    Cities = new HashSet<City>(); 
    //}
    public int CountryId { get; set; }

    public string Name { get; set; }

    public virtual ICollection<City> Cities { get; set; }  = new List<City>();
}